# Generated by Django 2.0.3 on 2018-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180330_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(default='', max_length=300, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
