# Generated by Django 2.0.3 on 2018-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180415_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(verbose_name='Content en'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=300, verbose_name='Slug en'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title en'),
        ),
    ]
