# Generated by Django 2.0.3 on 2018-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
